# Verwende den offiziellen Node.js-Image
FROM node:18

# Arbeitsverzeichnis erstellen
WORKDIR /app

# Kopiere die package.json und package-lock.json
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den Rest der Anwendung
COPY ./ .

# Exponiere den Port
EXPOSE 3000

# Starte die Anwendung
CMD ["npm", "start"]
